module:
    revision: 1
    group: 'cms-blocks'
    edit_template: '@module/block_static/edit.html.twig'
    form_template: '@module/block_static/form.html.twig'
    render_template: '@module/block_static/render.html.twig'
    module_options:
        label_format: 'modules.block_static.%%name%%.label'
        translation_domain: 'custom_domain'
        form_fields:
            id:
                type: 'id'

            class:
                type: 'class'

            block:
                type: 'blockStatic'
