services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_cms.entity_manager'
            $siteRouteParamName: '%sfs_cms.site.route_param_name%'
            $twigAppVariable: '@twig.app_variable'
            $findParamName: '%sfs_cms.site.find_field_name%'

    Softspring\CmsBundle\EventListener\SiteDoctrineFilterListener:
        tags: ['kernel.event_subscriber']

    Softspring\CmsBundle\EventListener\SiteRequestListener:
        tags: ['kernel.event_subscriber']
