parameters:
    sfs_cms.admin.sites.list_view: '@@SfsCms/admin/site/list.html.twig'
    sfs_cms.admin.sites.list_page_view: '@@SfsCms/admin/site/list-page.html.twig'
    sfs_cms.admin.sites.create_view: '@@SfsCms/admin/site/create.html.twig'
    sfs_cms.admin.sites.update_view: '@@SfsCms/admin/site/update.html.twig'
    sfs_cms.admin.sites.delete_view: '@@SfsCms/admin/site/delete.html.twig'
    sfs_cms.admin.sites.read_view: '@@SfsCms/admin/site/read.html.twig'

services:
    sfs_cms.admin.site.controller:
        class: Softspring\CrudlBundle\Controller\CrudlController
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }
        arguments:
            $manager: '@Softspring\CmsBundle\Manager\SiteManagerInterface'
            $eventDispatcher: '@event_dispatcher'
            $listFilterForm: '@Softspring\CmsBundle\Form\Admin\Site\SiteListFilterFormInterface'
            $createForm: '@Softspring\CmsBundle\Form\Admin\Site\SiteCreateFormInterface'
            $updateForm: '@Softspring\CmsBundle\Form\Admin\Site\SiteUpdateFormInterface'
            $deleteForm: '@Softspring\CmsBundle\Form\Admin\Site\SiteDeleteFormInterface'
            $config:
                entity_attribute: 'site'
                list:
                    is_granted: 'ROLE_SFS_CMS_ADMIN_SITES_LIST'
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_LIST_VIEW
                    view: '%sfs_cms.admin.sites.list_view%'
                    view_page: '%sfs_cms.admin.sites.list_page_view%'
                create:
                    is_granted: 'ROLE_SFS_CMS_ADMIN_SITES_CREATE'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_CREATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_CREATE_FORM_VALID
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_CREATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_CREATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_CREATE_VIEW
                    success_redirect_to: 'sfs_cms_admin_sites_list'
                    view: '%sfs_cms.admin.sites.create_view%'
                update:
                    is_granted: 'ROLE_SFS_CMS_ADMIN_SITES_UPDATE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_UPDATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_UPDATE_FORM_VALID
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_UPDATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_UPDATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_UPDATE_VIEW
                    success_redirect_to: 'sfs_cms_admin_sites_list'
                    view: '%sfs_cms.admin.sites.update_view%'
                delete:
                    is_granted: 'ROLE_SFS_CMS_ADMIN_SITES_DELETE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_DELETE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_DELETE_FORM_VALID
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_DELETE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_DELETE_FORM_INVALID
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_DELETE_VIEW
                    success_redirect_to: 'sfs_cms_admin_sites_list'
                    view: '%sfs_cms.admin.sites.delete_view%'
                read:
                    is_granted: 'ROLE_SFS_CMS_ADMIN_SITES_DETAILS'
                    param_converter_key: 'id'
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_READ_VIEW
                    view: '%sfs_cms.admin.sites.read_view%'