parameters:
    sfs_cms.admin.pages.list_view: '@@SfsCms/admin/page/list.html.twig'
    sfs_cms.admin.pages.list_page_view: '@@SfsCms/admin/page/list-page.html.twig'
    sfs_cms.admin.pages.create_view: '@@SfsCms/admin/page/create.html.twig'
    sfs_cms.admin.pages.update_view: '@@SfsCms/admin/page/update.html.twig'
    sfs_cms.admin.pages.delete_view: '@@SfsCms/admin/page/delete.html.twig'
    sfs_cms.admin.pages.read_view: '@@SfsCms/admin/page/read.html.twig'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_cms.entity_manager'

    Softspring\CmsBundle\Form\Admin\Page\:
        resource: '../../../src/Form/Admin/Page/Page*'

    Softspring\CmsBundle\EventListener\Admin\:
        resource: '../../../src/EventListener/Admin/Page*'

    sfs_cms.admin.page.controller:
        class: Softspring\CrudlBundle\Controller\CrudlController
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }
        arguments:
            $manager: '@sfs_cms.admin.pages.manager'
            $eventDispatcher: '@event_dispatcher'
            #            $listFilterForm: '@Softspring\CmsBundle\Form\Admin\Page\PageListFilterFormInterface'
            #            $deleteForm: '@Softspring\CmsBundle\Form\Admin\Page\PageDeleteFormInterface'
            $listFilterForm: null
            $createForm: '@Softspring\CmsBundle\Form\Admin\Page\PageCreateFormInterface'
            $updateForm: '@Softspring\CmsBundle\Form\Admin\Page\PageUpdateFormInterface'
            $deleteForm: null
            $config:
                entity_attribute: 'page'
                list:
                    is_granted: 'ROLE_SFS_CMS_ADMIN_PAGES_LIST'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_LIST_INITIALIZE
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_LIST_VIEW
                    view: '%sfs_cms.admin.pages.list_view%'
                    view_page: '%sfs_cms.admin.pages.list_page_view%'
                create:
                    is_granted: 'ROLE_SFS_CMS_ADMIN_PAGES_CREATE'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_CREATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_CREATE_FORM_VALID
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_CREATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_CREATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_CREATE_VIEW
                    success_redirect_to: 'sfs_cms_admin_pages_list'
                    view: '%sfs_cms.admin.pages.create_view%'
                update:
                    is_granted: 'ROLE_SFS_CMS_ADMIN_PAGES_UPDATE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_UPDATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_UPDATE_FORM_VALID
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_UPDATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_UPDATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_UPDATE_VIEW
                    success_redirect_to: 'sfs_cms_admin_pages_list'
                    view: '%sfs_cms.admin.pages.update_view%'
                delete:
                    is_granted: 'ROLE_SFS_CMS_ADMIN_PAGES_DELETE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_DELETE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_DELETE_FORM_VALID
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_DELETE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_DELETE_FORM_INVALID
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_DELETE_VIEW
                    success_redirect_to: 'sfs_cms_admin_pages_list'
                    view: '%sfs_cms.admin.pages.delete_view%'
                read:
                    is_granted: 'ROLE_SFS_CMS_ADMIN_PAGES_DETAILS'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_READ_INITIALIZE
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_READ_VIEW
                    view: '%sfs_cms.admin.pages.read_view%'
