parameters:
    sfs_cms.admin.blocks.list_view: '@@SfsCms/admin/block/list.html.twig'
    sfs_cms.admin.blocks.list_page_view: '@@SfsCms/admin/block/list-page.html.twig'
    sfs_cms.admin.blocks.create_view: '@@SfsCms/admin/block/create.html.twig'
    sfs_cms.admin.blocks.update_view: '@@SfsCms/admin/block/update.html.twig'
    sfs_cms.admin.blocks.delete_view: '@@SfsCms/admin/block/delete.html.twig'
    sfs_cms.admin.blocks.read_view: '@@SfsCms/admin/block/read.html.twig'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $blockTypes: '%sfs_cms.block.types%'
#            $em: '@sfs_cms.entity_manager'

    Softspring\CmsBundle\Form\Admin\:
        resource: '../../../src/Form/Admin/Block*'

    Softspring\CmsBundle\EventListener\Admin\:
        resource: '../../../src/EventListener/Admin/Block*'

    sfs_cms.admin.block.controller:
        class: Softspring\CrudlBundle\Controller\CrudlController
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }
        arguments:
            $manager: '@Softspring\CmsBundle\Manager\BlockManagerInterface'
            $eventDispatcher: '@event_dispatcher'
            $listFilterForm: '@Softspring\CmsBundle\Form\Admin\BlockListFilterFormInterface'
            $createForm: '@Softspring\CmsBundle\Form\Admin\BlockCreateFormInterface'
            $updateForm: '@Softspring\CmsBundle\Form\Admin\BlockUpdateFormInterface'
            $deleteForm: '@Softspring\CmsBundle\Form\Admin\BlockDeleteFormInterface'
            $config:
                entity_attribute: 'block'
                list:
                    is_granted: 'ROLE_SFS_CMS_ADMIN_BLOCKS_LIST'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_LIST_INITIALIZE
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_LIST_VIEW
                    view: '%sfs_cms.admin.blocks.list_view%'
                    view_page: '%sfs_cms.admin.blocks.list_page_view%'
                create:
                    is_granted: 'ROLE_SFS_CMS_ADMIN_BLOCKS_CREATE'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_CREATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_CREATE_FORM_VALID
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_CREATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_CREATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_CREATE_VIEW
                    success_redirect_to: 'sfs_cms_admin_blocks_list'
                    view: '%sfs_cms.admin.blocks.create_view%'
                update:
                    is_granted: 'ROLE_SFS_CMS_ADMIN_BLOCKS_UPDATE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_UPDATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_UPDATE_FORM_VALID
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_UPDATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_UPDATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_UPDATE_VIEW
                    success_redirect_to: 'sfs_cms_admin_blocks_list'
                    view: '%sfs_cms.admin.blocks.update_view%'
                delete:
                    is_granted: 'ROLE_SFS_CMS_ADMIN_BLOCKS_DELETE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_DELETE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_DELETE_FORM_VALID
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_DELETE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_DELETE_FORM_INVALID
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_DELETE_VIEW
                    success_redirect_to: 'sfs_cms_admin_blocks_list'
                    view: '%sfs_cms.admin.blocks.delete_view%'
                read:
                    is_granted: 'ROLE_SFS_CMS_ADMIN_BLOCKS_DETAILS'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_READ_INITIALIZE
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_READ_VIEW
                    view: '%sfs_cms.admin.blocks.read_view%'