# this is the page base configuration
content:
    revision: 1
    entity_class: 'Softspring\CmsBundle\Entity\Page'
    default_layout: 'default'
    seo:
        metaTitle:
            type: translatableText
        metaDescription:
            type: translatableText
        metaKeywords:
            type: translatableText
        noIndex:
            type: checkbox
            type_options:
                required: false
        noFollow:
            type: checkbox
            type_options:
                required: false
        sitemap:
            type: checkbox
            type_options:
                required: false
        sitemapChangefreq:
            type: choice
            type_options:
                choices:
                    "": false
                    always: always
                    hourly: hourly
                    daily: daily
                    weekly: weekly
                    monthly: monthly
                    yearly: yearly
                    never: never
        sitemapPriority:
            type: number
            type_options:
                required: false
                scale: 1
                constraints:
                    - { constraint: range, options: { min: 0, max: 1 } }