# this is the page base configuration
content:
    revision: 1
    entity_class: 'Softspring\CmsBundle\Entity\Page'
    default_layout: 'default'
    seo:
        metaTitle:
            type: translatableText
        metaDescription:
            type: translatableText
        metaKeywords:
            type: translatableText
        noIndex:
            type: checkbox
            type_options:
                required: false
        noFollow:
            type: checkbox
            type_options:
                required: false
        sitemap:
            type: checkbox
            type_options:
                required: false