list:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::list
    path: /

create:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::create
    path: /create

import:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::import
    path: /import

details:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::read
    path: /{content}

preview:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::preview
    path: /{content}/preview

preview_version:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::preview
    path: /{content}/{version}/preview

update:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::update
    path: /{content}/update

seo:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::seo
    path: /{content}/seo

content:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::content
    path: /{content}/content

content_from_version:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::content
    path: /{content}/{prevVersion}/content

preview_content:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController:previewContent
    path: /{content}/preview-content

preview_content_version:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController:previewContent
    path: /{content}/{version}/preview-content

publish_version:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController:publishVersion
    path: /{content}/{version}/publish-version

keep_version:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController:markKeepVersion
    path: /{content}/{version}/keep-version
    defaults:
        keep: true

unkeep_version:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController:markKeepVersion
    path: /{content}/{version}/unkeep-version
    defaults:
        keep: false

export_version:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController:exportVersion
    path: /{content}/{version}/export-version

versions:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::versions
    path: /{content}/versions

cleanup_versions:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::cleanupVersions
    path: /{content}/cleanup-versions