sfs_cms_admin_sites_list:
    controller: sfs_cms.admin.site.controller::list
    path: /

sfs_cms_admin_sites_create:
    controller: sfs_cms.admin.site.controller::create
    path: /create

sfs_cms_admin_sites_update:
    controller: sfs_cms.admin.site.controller::update
    path: /{site}/update

sfs_cms_admin_sites_delete:
    controller: sfs_cms.admin.site.controller::delete
    path: /{site}/delete

sfs_cms_admin_sites_read:
    controller: sfs_cms.admin.site.controller::read
    path: /{site}
