sfs_cms_admin_pages_list:
    controller: sfs_cms.admin.page.controller::list
    path: /

sfs_cms_admin_pages_create:
    controller: sfs_cms.admin.page.controller::create
    path: /create

sfs_cms_admin_pages_details:
    controller: sfs_cms.admin.page.controller::read
    path: /{page}

sfs_cms_admin_pages_preview:
    controller: sfs_cms.admin.page.controller::read
    path: /{page}/preview
    defaults:
        config:
            view: '@SfsCms/admin/page/preview.html.twig'

sfs_cms_admin_pages_update:
    controller: sfs_cms.admin.page.controller::update
    path: /{page}/update

sfs_cms_admin_pages_content:
    controller: sfs_cms.admin.page.controller::update
    path: /{page}/content
    defaults:
        updateForm: 'Softspring\CmsBundle\Form\Admin\Page\PageContentForm'
        initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_CONTENT_INITIALIZE
        form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_CONTENT_FORM_VALID
        success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_CONTENT_SUCCESS
        form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_CONTENT_FORM_INVALID
        view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_CONTENT_VIEW
        config:
            view: '@SfsCms/admin/page/content.html.twig'

sfs_cms_admin_pages_seo:
    controller: sfs_cms.admin.page.controller::update
    path: /{page}/seo
    defaults:
        updateForm: 'Softspring\CmsBundle\Form\Admin\Page\PageSeoForm'
        initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_SEO_INITIALIZE
        form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_SEO_FORM_VALID
        success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_SEO_SUCCESS
        form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_SEO_FORM_INVALID
        view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_PAGES_SEO_VIEW
        config:
            view: '@SfsCms/admin/page/seo.html.twig'

sfs_cms_admin_pages_preview_content:
    controller: Softspring\CmsBundle\Controller\Admin\PageController:preview
    path: /{page}/preview-content

sfs_cms_admin_pages_translations:
    controller: Softspring\TranslationBundle\Controller\Admin\ObjectTranslationsController::listTranslations
    path: /{entity}/translations
    defaults:
        entityClass: Softspring\CmsBundle\Model\PageInterface
        extendedTemplate: '@SfsCms/admin/page/translations.html.twig'