list:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::list
    path: /

create:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::create
    path: /create

details:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::read
    path: /{content}

preview:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::preview
    path: /{content}/preview

preview_version:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::preview
    path: /{content}/preview/{version}

update:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::update
    path: /{content}/update

seo:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::seo
    path: /{content}/seo

content:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::content
    path: /{content}/content

content_from_version:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::content
    path: /{content}/content/{prevVersion}

preview_content:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController:previewContent
    path: /{content}/preview-content

preview_content_version:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController:previewContent
    path: /{content}/preview-content/{version}

publish_version:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController:publishVersion
    path: /{content}/publish-version/{version}

versions:
    controller: Softspring\CmsBundle\Controller\Admin\ContentController::versions
    path: /{content}/versions