module:
    revision: 2
    group: 'container'
    edit_template: '@module/container/edit.html.twig'
    form_template: '@module/container/form.html.twig'
    module_type: 'Softspring\CmsBundle\Form\Module\ContainerModuleType'
    module_options:
        module_collection_class: 'container'
        module_row_class: 'row'
        allowed_modules: ~
        allowed_container_modules: ~
        form_fields:
            id:
                type: 'id'

            class:
                type: 'class'
                
            container_type:
                type: 'choice'
                type_options:
                    default_value: 'container'
                    choices:
                        "container.form.container_type.values.container": 'container'
                        "container.form.container_type.values.fluid": 'container-fluid'
                        
            tag_type:
                type: 'choice'
                type_options:
                    default_value: 'div'
                    choices:
                        "container.form.tag_type.values.div": 'div'
                        "container.form.tag_type.values.section": 'section'
                        "container.form.tag_type.values.article": 'article'

            bg_color:
                type: 'color'
