module:
    revision: 1
    group: 'container'
    edit_template: '@module/container/edit.html.twig'
    module_type: 'Softspring\CmsBundle\Form\Module\ContainerModuleType'
    module_options:
        module_collection_class: 'container'
        module_row_class: 'row'
        allowed_modules: ~
        allowed_container_modules:
            - grid
            - container
        form_fields:
            id:
                type: 'id'
                type_options:
                    attr:
                        data-edit-id-input: 'containerIdDiv'

            class:
                type: 'class'
                type_options:
                    attr:
                        data-edit-class-input: 'containerClassDiv'

            bg_color:
                type: 'color'
                type_options:
                    attr:
                        data-edit-bgcolor-input: 'containerColorDiv'