module:
    revision: 1
    group: 'html'
    edit_template: '@module/html/edit.html.twig'
    form_template: '@module/html/form.html.twig'
    render_template: '@module/html/render.html.twig'
    module_options:
        label_format: 'modules.html.%%name%%.label'
        translation_domain: 'custom_domain'
        form_fields:
            id:
                type: 'id'

            class:
                type: 'class'

            code:
                type: 'html'
                type_options:
                    attr:
                        style: 'min-height: 400px'
