Softspring\CmsBundle\Model\RoutePathInterface:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['path', 'locale', 'site']
            ignoreNull: false