Softspring\CmsBundle\Model\RoutePathInterface:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['path', 'locale'] # todo and route.site
            ignoreNull: false