security:
    role_hierarchy:

        ROLE_SFS_CMS_ADMIN_BLOCKS_RO:
            - ROLE_SFS_CMS_ADMIN_BLOCKS_LIST
            - ROLE_SFS_CMS_ADMIN_BLOCKS_DETAILS
        ROLE_SFS_CMS_ADMIN_BLOCKS_RW:
            - ROLE_SFS_CMS_ADMIN_BLOCKS_RO
            - ROLE_SFS_CMS_ADMIN_BLOCKS_CREATE
            - ROLE_SFS_CMS_ADMIN_BLOCKS_DELETE
            - ROLE_SFS_CMS_ADMIN_BLOCKS_UPDATE

        ROLE_SFS_CMS_ADMIN_SITES_RO:
            - ROLE_SFS_CMS_ADMIN_SITES_LIST
            - ROLE_SFS_CMS_ADMIN_SITES_DETAILS
        ROLE_SFS_CMS_ADMIN_SITES_RW:
            - ROLE_SFS_CMS_ADMIN_SITES_RO
            - ROLE_SFS_CMS_ADMIN_SITES_CREATE
            - ROLE_SFS_CMS_ADMIN_SITES_DELETE
            - ROLE_SFS_CMS_ADMIN_SITES_UPDATE

        ROLE_SFS_CMS_ADMIN_ROUTES_RO:
            - ROLE_SFS_CMS_ADMIN_ROUTES_LIST
            - ROLE_SFS_CMS_ADMIN_ROUTES_DETAILS
        ROLE_SFS_CMS_ADMIN_ROUTES_RW:
            - ROLE_SFS_CMS_ADMIN_ROUTES_RO
            - ROLE_SFS_CMS_ADMIN_ROUTES_CREATE
            - ROLE_SFS_CMS_ADMIN_ROUTES_DELETE
            - ROLE_SFS_CMS_ADMIN_ROUTES_UPDATE

        ROLE_SFS_CMS_ADMIN_PAGES_RO:
            - ROLE_SFS_CMS_ADMIN_PAGES_LIST
            - ROLE_SFS_CMS_ADMIN_PAGES_DETAILS
        ROLE_SFS_CMS_ADMIN_PAGES_RW:
            - ROLE_SFS_CMS_ADMIN_PAGES_RO
            - ROLE_SFS_CMS_ADMIN_PAGES_CREATE
            - ROLE_SFS_CMS_ADMIN_PAGES_DELETE
            - ROLE_SFS_CMS_ADMIN_PAGES_UPDATE