services:
    sfs_cms.admin.site.controller:
        class: Softspring\CrudlBundle\Controller\CrudlController
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }
        arguments:
            $manager: '@Softspring\CmsBundle\Manager\SiteManagerInterface'
            $listFilterForm: '@Softspring\CmsBundle\Form\Admin\SiteListFilterFormInterface'
            $createForm: '@Softspring\CmsBundle\Form\Admin\SiteCreateFormInterface'
            $updateForm: '@Softspring\CmsBundle\Form\Admin\SiteUpdateFormInterface'
            $deleteForm: '@Softspring\CmsBundle\Form\Admin\SiteDeleteFormInterface'
            $config:
                entity_attribute: 'site'
                list:
                    is_granted: 'ROLE_ADMIN_SITE_LIST'
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_LIST_VIEW
                    view: '@@SfsCms/admin/site/list.html.twig'
                    view_page: '@@SfsCms/admin/site/list-page.html.twig'
                create:
                    is_granted: 'ROLE_ADMIN_SITE_CREATE'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_CREATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_CREATE_FORM_VALID
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_CREATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_CREATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_CREATE_VIEW
                    success_redirect_to: 'sfs_cms_admin_sites_list'
                    view: '@@SfsCms/admin/site/create.html.twig'
                update:
                    is_granted: 'ROLE_ADMIN_SITE_UPDATE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_UPDATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_UPDATE_FORM_VALID
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_UPDATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_UPDATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_UPDATE_VIEW
                    success_redirect_to: 'sfs_cms_admin_sites_list'
                    view: '@@SfsCms/admin/site/update.html.twig'
                delete:
                    is_granted: 'ROLE_ADMIN_SITE_DELETE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_DELETE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_DELETE_FORM_VALID
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_DELETE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_DELETE_FORM_INVALID
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_DELETE_VIEW
                    success_redirect_to: 'sfs_cms_admin_sites_list'
                    view: '@@SfsCms/admin/site/delete.html.twig'
                read:
                    is_granted: 'ROLE_ADMIN_SITE_READ'
                    param_converter_key: 'id'
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SITES_READ_VIEW
                    view: '@@SfsCms/admin/site/read.html.twig'